version: "3"
services:
  api:
    extends: 
      file: docker-compose.api.yml
      service: api
    depends_on:
      - rmq
  app:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    restart: always
    container_name: app
    ports:
      - 3001:80
    networks:
      - myNetwork
  converter:
    build:
      context: .
      dockerfile: ./apps/converter/Dockerfile
    restart: always
    container_name: converter
    volumes:
      - ./.env:/opt/app/.env
    networks:
      - myNetwork
    depends_on:
      - rmq
  rmq:
    image: rabbitmq:3-management
    networks:
      - myNetwork
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  myNetwork:
    driver: bridge
